import { Inter } from "next/font/google";
import "../globals.scss";

import { Header, RightSideBar } from "@/components";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CMS Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="container mx-auto px mb-8">
          <section className="grid grid-cols-1 lg:grid-cols-12 gap-12">
            {children}
            <RightSideBar />
          </section>
        </main>
      </body>
    </html>
  );
}
