import { Inter } from "next/font/google";
import "../globals.css";
import RightSideBar from "@/components/shared/RightSideBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "CMS Blog",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="container mx-auto px mb-8">
          <section>{children}</section>
          <RightSideBar />
        </main>
      </body>
    </html>
  );
}
